### ISSUE TITLE
Doesn't Build or Run

### ISSUE THREAD

**Issue by BenjaminHCCarr** [dlion/go-odbye#3]
I have a correct json file, and have tried both building and running it:

https://domenicoluciani.com/2016/08/29/go-odbye.html

go run main.go -nick twitter_nick

and

go build main.go

both fail with the same errors, I think your import isn't working right.

Error:

```
tyr:~/Code/github/go-odbye (master) benc$ go build main.go
main.go:8:2: cannot find package "github.com/dghubble/go-twitter/twitter" in any of:
    /usr/local/Cellar/go/1.7.1/libexec/src/github.com/dghubble/go-twitter/twitter (from $GOROOT)
    /Users/benc/.gocode/src/github.com/dghubble/go-twitter/twitter (from $GOPATH)
main.go:9:2: cannot find package "github.com/dghubble/oauth1" in any of:
    /usr/local/Cellar/go/1.7.1/libexec/src/github.com/dghubble/oauth1 (from $GOROOT)
    /Users/benc/.gocode/src/github.com/dghubble/oauth1 (from $GOPATH)
main.go:10:2: cannot find package "github.com/fatih/color" in any of:
    /usr/local/Cellar/go/1.7.1/libexec/src/github.com/fatih/color (from $GOROOT)
    /Users/benc/.gocode/src/github.com/fatih/color (from $GOPATH)
main.go:11:2: cannot find package "github.com/mattn/go-sqlite3" in any of:
    /usr/local/Cellar/go/1.7.1/libexec/src/github.com/mattn/go-sqlite3 (from $GOROOT)
    /Users/benc/.gocode/src/github.com/mattn/go-sqlite3 (from $GOPATH)
```

In .bashrc I have:

```
GOPATH="$HOME/.gocode"
export GOPATH
```

which has worked fine for my other go projects.

**Comment by dlion** [comment]
Obviously to run/build it you need to get the dependencies, reading your message:
`cannot find package "github.com/dghubble/go-twitter/twitter"`, so type `go get github.com/dghubble/go-twitter/twitter` on your console to get it, do the same for `github.com/dghubble/oauth1`, `github.com/fatih/color` and `github.com/mattn/go-sqlite3` packages.

**Comment by BenjaminHCCarr** [comment]
Correct, which is why I thought the import was failing, having not programmed Go, only run toosl, I assumed like most modern languages that it would do dependency fulfillment through the import function, but apparently not.

I knew the dependancies were failing, I just didn't know I needed to do it all the requirements by hand. You have 12 imports, which poses an impediment to running what looked like a great resource. I simply assumed that Go at this point had dependency management.

**Comment by dlion** [comment]
You are right, to do this automagically you can type `go get` and it will resolve the dependencies without interaction, I told you why and how to fix your error just to teach you how these things work :mortar_board:

**Comment by BenjaminHCCarr** [comment]
Oh thanks, for that clarification, that is useful for those that use go, but don't code it. You might want to update your webpage and Readme, as they call for calling main.go in two different ways, neither of which fetches dependancies.

Adding a first run/prep line to both pages would be super useful for those of us who do R/Python/Perl/ruby and packaging of different managers with automatic dep management, who haven't gone the golang way yet.

**Comment by dlion** [comment]
Of course, I will update a both, thank you for your feedback and suggestions!

**Comment by BenjaminHCCarr** [comment]
Thanks so much, I was able to get it to build. I did run into one little bump though. I had to copy your cloned tree to $GOPATH/src to make the go get work.

Just as an fyi.

**Comment by BenjaminHCCarr** [comment]
Oh, I do however love the tool!
