### ISSUE TITLE
error: cannot use int(cursor) (type int) as type int64 in field value

### ISSUE THREAD

**Issue by donatj** [dlion/go-odbye#4]
I tried to go get -u to get a newer version of this and it throws:

```
../../gocode/src/github.com/dlion/go-odbye/main.go:110: cannot use int(cursor) (type int) as type int64 in field value
```

**Comment by BenjaminHCCarr** [comment]
interesting, I had the exact opposite problem:
```
tyr:~/.gocode/src/go-odbye (master) benc$ go get
# go-odbye
./main.go:115: cannot use int64(cursor) (type int64) as type int in field value
```

same resolution though; run: `go get -u`

**Comment by dlion** [comment]
@BenjaminHCCarr very strange, using the @donatj's solution it works fine for me
Mmmh are you using an 64bit machine?

Anyway good, using `go get -u` should be fine

**Comment by BenjaminHCCarr** [comment]
@dlion yes, core i5. Something was just out of date somewhere upstream.
